### ISSUE TITLE
Error in getting mbox to csv!

### ISSUE THREAD

**Issue by koutkout** [pizzato/LLMMe#1]
2023-10-16 13:04:59,691 - Indexing emails
2023-10-16 13:07:54,946 - Indexed 16043 emails
2023-10-16 13:07:54,946 - Creating dataframe
2023-10-16 13:07:55,837 - Getting email content
2023-10-16 13:09:48,972 - Getting replies
2023-10-16 13:09:49,061 - Dataset (total replies  53)
2023-10-16 13:09:49,086 - Getting original emails sent
2023-10-16 13:09:49,112 - Dataset (total new emails  177)
2023-10-16 13:09:49,137 - Dataset (total emails received 0)
Traceback (most recent call last):
  File "\LLMMe\convert_mbox_to_csv.py", line 159, in <module>
    create_email_csv_dataset(mbox_filename=args.input, my_email_addresses=args.emails, csv_file_output=args.output)
  File "\LLMMe\convert_mbox_to_csv.py", line 130, in create_email_csv_dataset
    messages_received_not_replied = messages_received_not_replied.sample(n=len(emails_replied) + len(emails_i_started))
  File \Python\Python310\site-packages\pandas\core\generic.py", line 5858, in sample
    sampled_indices = sample.sample(obj_len, size, replace, weights, rs)
  File "\Python\Python310\site-packages\pandas\core\sample.py", line 151, in sample
    return random_state.choice(obj_len, size=size, replace=replace, p=weights).astype(
  File "mtrand.pyx", line 928, in numpy.random.mtrand.RandomState.choice
ValueError: a must be greater than 0 unless no samples are taken

**Comment by pizzato** [comment]
Hi @koutkout thanks for flagging this. It looks like that email address never received an email. Given that this returns 0 emails:
` messages_received = df[~df['From'].str.contains('|'.join(my_email_addresses), regex=True, na=False, case=False)]`

This was a recent addition to my script so you might have either might be that you didn't extract all emails, or this is not your mail mailbox. Nevertheless I'll work on a fix so that the script doesn't fails.

**Comment by koutkout** [comment]
Thanks. Please note that i am working on an mbox file from thunderbird. Maybe the format is a little bit different. 
Is there an earlier version that I can download before you made this change and try it out?

**Comment by pizzato** [comment]
That is a good point. Can you check the field names in your mbox file? Gmail uses "From" as written here, does thunderbird uses in a different capitalisation? Say: "from", or "FROM"?

I just pushed some changes to this branch that would prevent the error, but might not be the final solution.
